#!/usr/bin/env bash

#
echo '---' > ./index.md
echo 'layout: default' >> ./index.md
echo '---' >> ./index.md

sed 's/\[\(.*\)\](\(.*\))$/[\1](\2){:target="_blank"}/g' $readme > $newFile

# Batch create the other 
for readme in $(fd -t f 'README.md'); do
    echo "Processing $readme"
    newFile="${readme/README/index}"

    if [[ $readme != 'README.md' ]]; then
        # Modify standard markdown links
        sed 's/\[\(.*\)\](\(.*\))$/[\1](\2){:target="_blank"}/g' $readme > $newFile

        # Modify angle bracket links
        sed 's/<\(https\?:\/\/[^>]*\)>$/<\1>{:target="_blank"}/g' $readme > $newFile
    fi
done
