#!/usr/bin/env bash

# Display information about the tracker lists being fetched
echo 'Fetching tracker lists from:'
echo 'https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all.txt'
echo 'https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all_ip.txt'
echo 'https://cf.trackerslist.com/all.txt'

# Download tracker lists silently (-s flag) and save to temporary files
curl -s 'https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all.txt' -o ./trackers1.txt
curl -s 'https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_all_ip.txt' -o ./trackers2.txt
curl -s 'https://cf.trackerslist.com/all.txt' -o ./trackers3.txt

# Add a blank line to the first line of 'ultimate_trackers.txt'
# and Combine all lists into one ultimate list of BitTorrent trackers
echo '' > ./ultimate_trackers.txt
cat ./trackers1.txt ./trackers2.txt ./trackers3.txt >> ./ultimate_trackers.txt
